// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutytK15Yx9No_qmYXPDajpQRZsp1_tco',
    appId: '1:83357206713:web:0f0227cf19648478aef368',
    messagingSenderId: '83357206713',
    projectId: 'fir-auth-dbd86',
    authDomain: 'fir-auth-dbd86.firebaseapp.com',
    storageBucket: 'fir-auth-dbd86.appspot.com',
    measurementId: 'G-8Y0TD077M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfocpt4HfTEEF4lmhh3rBiWM3CbaRWZ9M',
    appId: '1:83357206713:android:764912868fd818b7aef368',
    messagingSenderId: '83357206713',
    projectId: 'fir-auth-dbd86',
    storageBucket: 'fir-auth-dbd86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-rb6iF5Yvx4RAZn1ogTmdIjHsFREehQ',
    appId: '1:83357206713:ios:c2f3e000f5a40fdaaef368',
    messagingSenderId: '83357206713',
    projectId: 'fir-auth-dbd86',
    storageBucket: 'fir-auth-dbd86.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi-rb6iF5Yvx4RAZn1ogTmdIjHsFREehQ',
    appId: '1:83357206713:ios:25d236e894d22dd9aef368',
    messagingSenderId: '83357206713',
    projectId: 'fir-auth-dbd86',
    storageBucket: 'fir-auth-dbd86.appspot.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
